'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'id' | 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  id: {
    'nav.home': 'Beranda',
    'nav.about': 'Tentang',
    'nav.contact': 'Kontak',
    'hero.title': 'SafCom',
    'hero.subtitle': 'Membangun solusi teknologi masa depan dengan integritas dan inovasi.',
    'hero.contact': 'Hubungi Kami',
    'hero.learn': 'Pelajari Lebih Lanjut',
    'about.title': 'Tentang SafCom',
    'about.description': 'Kami adalah perusahaan teknologi yang berpikir maju yang berkomitmen untuk menciptakan solusi inovatif yang mendorong transformasi digital dan memberdayakan bisnis di seluruh dunia.',
    'about.preview.description': 'Kami percaya teknologi bukan hanya alat, tetapi masa depan. Melalui inovasi, kolaborasi, dan solusi berkelanjutan, kami membangun generasi berikutnya dari pengalaman digital.',
    'about.preview.button': 'Pelajari Lebih Lanjut Tentang Kami',
    'about.vision.title': 'Visi Kami',
    'about.vision.content': 'Menjadi pemimpin global dalam solusi teknologi inovatif yang mendorong kemajuan manusia dan keberlanjutan planet.',
    'about.mission.title': 'Misi Kami',
    'about.mission.content': 'Mengembangkan teknologi canggih yang etis, aman, dan bermanfaat bagi masyarakat, sambil membangun kemitraan yang kuat untuk mencapai hasil luar biasa.',
    'about.values.title': 'Nilai-Nilai Kami',
    'about.values.integrity.title': 'Integritas',
    'about.values.integrity.desc': 'Kami menjunjung standar tertinggi dalam kejujuran dan praktik etis di semua yang kami lakukan.',
    'about.values.collaboration.title': 'Kolaborasi',
    'about.values.collaboration.desc': 'Kami percaya pada kekuatan kerja tim dan kemitraan untuk mencapai hasil luar biasa.',
    'about.values.sustainability.title': 'Keberlanjutan',
    'about.values.sustainability.desc': 'Kami berkomitmen untuk menciptakan teknologi yang bermanfaat bagi manusia dan planet.',
    'about.milestones.title': 'Perjalanan Kami',
    'about.milestones.2018': 'Didirikan SafCom',
    'about.milestones.2020': 'Berkembang ke solusi cloud',
    'about.milestones.2022': 'Meluncurkan divisi penelitian AI',
    'about.milestones.2024': 'Mencapai sertifikasi ISO 27001',
    'about.cta': 'Bergabunglah dengan Kami',
    'about.cta.title': 'Mari Bangun Masa Depan Bersama',
    'about.cta.subtitle': 'Bergabunglah dengan kami dalam menciptakan solusi inovatif yang membuat perbedaan.',
    'about.cta.description': 'Siap untuk berkolaborasi? Mari diskusikan proyek Anda dan jelajahi bagaimana SafCom dapat membantu mewujudkan visi Anda.',
    'about.cta.button': 'Hubungi Kami',
    'about.journey.title': 'Perjalanan Kami',
    'contact.title': 'Hubungi Kami',
    'contact.subtitle': 'Siap untuk memulai proyek Anda berikutnya? Mari kita diskusikan bagaimana kami dapat membantu Anda.',
    'contact.preview.title': 'Siap Berkolaborasi?',
    'contact.preview.description': 'Mari diskusikan proyek Anda dan jelajahi bagaimana SafCom dapat membantu mewujudkan visi Anda.',
    'contact.preview.button': 'Hubungi Kami',
    'contact.form.name': 'Nama',
    'contact.form.namePlaceholder': 'Masukkan nama Anda',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'Masukkan alamat email Anda',
    'contact.form.message': 'Pesan',
    'contact.form.messagePlaceholder': 'Tuliskan pesan Anda di sini...',
    'contact.form.submit': 'Kirim Pesan',
    'contact.form.title': 'Kirim Pesan kepada Kami',
    'contact.form.sending': 'Mengirim...',
    'contact.form.success': 'Pesan berhasil dikirim!',
    'contact.form.error': 'Terjadi kesalahan. Silakan coba lagi.',
    'contact.info.title': 'Informasi Kontak',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Telepon',
    'contact.info.address': 'Alamat',
    'contact.info.location': 'Lokasi',
    'contact.info.follow': 'Ikuti Kami',
    'contact.info.followDesc': 'Terhubung dengan kami di platform media sosial untuk update terbaru dan berita teknologi.',
    'contact.follow.title': 'Ikuti Kami',
    'contact.follow.linkedin': 'LinkedIn',
    'contact.follow.github': 'GitHub',
    'contact.follow.twitter': 'X',
    'contact.follow.instagram': 'Instagram',
    'footer.about.title': 'Tentang Kami',
    'footer.about.description': 'Kami adalah perusahaan teknologi yang berkomitmen untuk menciptakan solusi inovatif yang berdampak positif pada masyarakat dan planet.',
    'footer.quicklinks': 'Tautan Cepat',
    'footer.services': 'Layanan',
    'services.subtitle': 'Transformasikan bisnis Anda dengan solusi teknologi mutakhir kami',
    'services.cta': 'Mulai Hari Ini',
    'footer.contact': 'Kontak',
    'footer.follow': 'Ikuti Kami',
    'footer.copyright': '© {year} SafCom oleh Safar & Safarudin. Seluruh Hak Dilindungi.',
    'footer.services.web': 'Pengembangan Web',
    'footer.services.mobile': 'Aplikasi Mobile',
    'footer.services.cloud': 'Solusi Cloud',
    'footer.services.ai': 'AI & Machine Learning',
    'services.web.description': 'Solusi perangkat lunak khusus yang disesuaikan dengan kebutuhan bisnis Anda, dibangun dengan teknologi modern dan praktik terbaik.',
    'services.mobile.description': 'Aplikasi mobile native dan cross-platform untuk iOS dan Android dengan pengalaman pengguna yang luar biasa.',
    'services.cloud.description': 'Solusi cloud yang dapat diskalakan di Azure, AWS, atau GCP untuk memastikan aplikasi Anda berjalan efisien dan aman.',
    'services.ai.description': 'Solusi AI mutakhir termasuk model machine learning, analitik data, dan otomasi cerdas.',
    'team.title': 'Temui Tim Kami',
    'team.subtitle': 'Innovator passion yang mendorong masa depan teknologi bersama',
    'team.autoplay.pause': 'Jeda Auto-putar',
    'team.autoplay.resume': 'Lanjutkan Auto-putar',
    'team.members.1.name': 'Alex Johnson',
    'team.members.1.role': 'Kepala Teknologi',
    'team.members.1.bio': 'Ahli pengembangan full-stack dengan pengalaman lebih dari 10 tahun. Spesialis dalam merancang arsitektur yang dapat diskalakan dan solusi cloud.',
    'team.members.2.name': 'Sarah Chen',
    'team.members.2.role': 'Desainer UX/UI',
    'team.members.2.bio': 'Spesialis desain yang memadukan kegunaan dan keindahan. Memahami kebutuhan pengguna dan memberikan solusi inovatif.',
    'team.members.3.name': 'Mike Rodriguez',
    'team.members.3.role': 'Pengembang Backend',
    'team.members.3.bio': 'Ahli desain database dan pengembangan API. Membangun sistem yang kuat dengan penekanan pada performa dan keamanan.',
    'team.members.4.name': 'Emma Williams',
    'team.members.4.role': 'Pengembang Frontend',
    'team.members.4.bio': 'Spesialis React dan Vue.js. Membuat antarmuka pengguna yang interaktif dan responsif.',
    'team.members.5.name': 'David Lee',
    'team.members.5.role': 'Insinyur DevOps',
    'team.members.5.bio': 'Spesialis pipeline CI/CD dan otomasi infrastruktur. Membangun proses deployment yang efisien dan andal.',
    'team.members.6.name': 'Lisa Garcia',
    'team.members.6.role': 'Manajer Proyek',
    'team.members.6.bio': 'Ahli metodologi Agile. Mengumpulkan tim dan memimpin proyek hingga sukses tepat waktu.',
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.title': 'SafCom',
    'hero.subtitle': 'Building future technology solutions with integrity and innovation.',
    'hero.contact': 'Contact Us',
    'hero.learn': 'Learn More',
    'about.title': 'About SafCom',
    'about.description': 'We are a forward-thinking technology company dedicated to creating innovative solutions that drive digital transformation and empower businesses worldwide.',
    'about.preview.description': 'We believe technology is not just a tool, but the future. Through innovation, collaboration, and sustainable solutions, we build the next generation of digital experiences.',
    'about.preview.button': 'Learn More About Us',
    'about.vision.title': 'Our Vision',
    'about.vision.content': 'To be a global leader in innovative technology solutions that drive human progress and planetary sustainability.',
    'about.mission.title': 'Our Mission',
    'about.mission.content': 'To develop advanced, ethical, and secure technologies that benefit society, while building strong partnerships to achieve extraordinary results.',
    'about.values.title': 'Our Values',
    'about.values.integrity.title': 'Integrity',
    'about.values.integrity.desc': 'We uphold the highest standards of honesty and ethical practices in everything we do.',
    'about.values.collaboration.title': 'Collaboration',
    'about.values.collaboration.desc': 'We believe in the power of teamwork and partnerships to achieve extraordinary results.',
    'about.values.sustainability.title': 'Sustainability',
    'about.values.sustainability.desc': 'We are committed to creating technology that benefits both people and the planet.',
    'about.milestones.title': 'Our Journey',
    'about.milestones.2018': 'Founded SafCom',
    'about.milestones.2020': 'Expanded to cloud solutions',
    'about.milestones.2022': 'Launched AI research division',
    'about.milestones.2024': 'Achieved ISO 27001 certification',
    'about.cta': 'Join Us',
    'about.cta.title': "Let's Build the Future Together",
    'about.cta.subtitle': 'Join us in creating innovative solutions that make a difference.',
    'about.cta.description': 'Ready to Collaborate? Let\'s discuss your project and explore how SafCom can help bring your vision to life.',
    'about.cta.button': 'Contact Us',
    'about.journey.title': 'Our Journey',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Ready to start your next project? Let\'s discuss how we can help you.',
    'contact.preview.title': 'Ready to Collaborate?',
    'contact.preview.description': 'Let\'s discuss your project and explore how SafCom can help bring your vision to life.',
    'contact.preview.button': 'Get In Touch',
    'contact.form.name': 'Name',
    'contact.form.namePlaceholder': 'Enter your name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'Enter your email address',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Write your message here...',
    'contact.form.submit': 'Send Message',
    'contact.form.title': 'Send Us a Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully!',
    'contact.form.error': 'An error occurred. Please try again.',
    'contact.info.title': 'Contact Information',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.address': 'Address',
    'contact.info.location': 'Location',
    'contact.info.follow': 'Follow Us',
    'contact.info.followDesc': 'Connect with us on social media platforms for the latest updates and technology news.',
    'contact.follow.title': 'Follow Us',
    'contact.follow.linkedin': 'LinkedIn',
    'contact.follow.github': 'GitHub',
    'contact.follow.twitter': 'X',
    'contact.follow.instagram': 'Instagram',
    'footer.about.title': 'About Us',
    'footer.about.description': 'We are a technology company committed to creating innovative solutions that positively impact society and the planet.',
    'footer.quicklinks': 'Quick Links',
    'footer.services': 'Services',
    'services.subtitle': 'Transform your business with our cutting-edge technology solutions',
    'services.cta': 'Get Started Today',
    'footer.contact': 'Contact',
    'footer.follow': 'Follow Us',
    'footer.copyright': '© {year} SafCom by Safar & Safarudin. All Rights Reserved.',
    'footer.services.web': 'Web Development',
    'footer.services.mobile': 'Mobile Apps',
    'footer.services.cloud': 'Cloud Solutions',
    'footer.services.ai': 'AI & Machine Learning',
    'services.web.description': 'Custom software solutions tailored to your business needs, built with modern technologies and best practices.',
    'services.mobile.description': 'Native and cross-platform mobile applications for iOS and Android with exceptional user experiences.',
    'services.cloud.description': 'Scalable cloud solutions on Azure, AWS, or GCP to ensure your applications run efficiently and securely.',
    'services.ai.description': 'Cutting-edge AI solutions including machine learning models, data analytics, and intelligent automation.',
    'team.title': 'Meet Our Team',
    'team.subtitle': 'Passionate innovators driving the future of technology together',
    'team.autoplay.pause': 'Pause Auto-play',
    'team.autoplay.resume': 'Resume Auto-play',
    'team.members.1.name': 'Alex Johnson',
    'team.members.1.role': 'Chief Technology Officer',
    'team.members.1.bio': 'Full-stack development expert with over 10 years of experience. Specializes in designing scalable architectures and cloud solutions.',
    'team.members.2.name': 'Sarah Chen',
    'team.members.2.role': 'UX/UI Designer',
    'team.members.2.bio': 'Design specialist who blends usability and beauty. Understands user needs and delivers innovative solutions.',
    'team.members.3.name': 'Mike Rodriguez',
    'team.members.3.role': 'Backend Developer',
    'team.members.3.bio': 'Database design and API development expert. Builds robust systems with emphasis on performance and security.',
    'team.members.4.name': 'Emma Williams',
    'team.members.4.role': 'Frontend Developer',
    'team.members.4.bio': 'React and Vue.js specialist. Creates interactive and responsive user interfaces.',
    'team.members.5.name': 'David Lee',
    'team.members.5.role': 'DevOps Engineer',
    'team.members.5.bio': 'CI/CD pipeline and infrastructure automation specialist. Builds efficient and reliable deployment processes.',
    'team.members.6.name': 'Lisa Garcia',
    'team.members.6.role': 'Project Manager',
    'team.members.6.bio': 'Agile methodology expert. Brings teams together and leads projects to success on time.',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.about': '会社概要',
    'nav.contact': 'お問い合わせ',
    'hero.title': 'SafCom',
    'hero.subtitle': '誠実さと革新性で未来の技術ソリューションを構築します。',
    'hero.contact': 'お問い合わせ',
    'hero.learn': '詳細を見る',
    'about.title': 'SafComについて',
    'about.description': '私たちは、デジタルトランスフォーメーションを推進し、世界中のビジネスに力を与える革新的なソリューションを作成することに取り組む先進的なテクノロジー企業です。',
    'about.preview.description': '私たちはテクノロジーが単なるツールではなく、未来であると信じています。イノベーション、コラボレーション、持続可能なソリューションを通じて、次世代のデジタル体験を構築します。',
    'about.preview.button': '私たちについて詳しく知る',
    'about.vision.title': '私たちのビジョン',
    'about.vision.content': '人間の進歩と地球の持続可能性を推進する革新的な技術ソリューションのグローバルリーダーとなること。',
    'about.mission.title': '私たちのミッション',
    'about.mission.content': '社会に利益をもたらす先進的で倫理的かつ安全な技術を開発し、卓越した成果を達成するための強力なパートナーシップを構築すること。',
    'about.values.title': '私たちの価値観',
    'about.values.integrity.title': '誠実さ',
    'about.values.integrity.desc': '私たちはすべてにおいて最高水準の誠実さと倫理的実践を維持します。',
    'about.values.collaboration.title': '協働',
    'about.values.collaboration.desc': '私たちはチームワークとパートナーシップの力を信じています。',
    'about.values.sustainability.title': '持続可能性',
    'about.values.sustainability.desc': '私たちは人間と地球の両方に利益をもたらす技術の創造に取り組んでいます。',
    'about.milestones.title': '私たちの軌跡',
    'about.milestones.2018': 'SafComを設立',
    'about.milestones.2020': 'クラウドソリューションに拡大',
    'about.milestones.2022': 'AI研究部門を立ち上げ',
    'about.milestones.2024': 'ISO 27001認証を取得',
    'about.cta': '私たちと一緒に',
    'about.cta.title': '一緒に未来を築きましょう',
    'about.cta.subtitle': '違いを生む革新的なソリューションの作成にご参加ください。',
    'about.cta.description': 'コラボレーションの準備はできましたか？プロジェクトについて議論し、SafComがどのようにビジョンを実現するお手伝いができるか探ってみましょう。',
    'about.cta.button': 'お問い合わせ',
    'about.journey.title': '私たちの軌跡',
    'contact.title': 'お問い合わせ',
    'contact.subtitle': '次のプロジェクトを開始する準備はできましたか？私たちがどのようにお手伝いできるか議論しましょう。',
    'contact.preview.title': 'コラボレーションの準備はできましたか？',
    'contact.preview.description': 'プロジェクトについて議論し、SafComがどのようにビジョンを実現するお手伝いができるか探ってみましょう。',
    'contact.preview.button': 'お問い合わせ',
    'contact.form.name': 'お名前',
    'contact.form.namePlaceholder': 'お名前を入力してください',
    'contact.form.email': 'メールアドレス',
    'contact.form.emailPlaceholder': 'メールアドレスを入力してください',
    'contact.form.message': 'メッセージ',
    'contact.form.messagePlaceholder': 'メッセージをここに書いてください...',
    'contact.form.submit': 'メッセージを送信',
    'contact.form.title': 'メッセージをお送りください',
    'contact.form.sending': '送信中...',
    'contact.form.success': 'メッセージが正常に送信されました！',
    'contact.form.error': 'エラーが発生しました。もう一度お試しください。',
    'contact.info.title': '連絡先情報',
    'contact.info.email': 'メール',
    'contact.info.phone': '電話',
    'contact.info.address': '住所',
    'contact.info.location': '場所',
    'contact.info.follow': 'フォローする',
    'contact.info.followDesc': 'ソーシャルメディアプラットフォームで最新のアップデートとテクノロジーニュースをご覧ください。',
    'contact.follow.title': 'フォローする',
    'contact.follow.linkedin': 'LinkedIn',
    'contact.follow.github': 'GitHub',
    'contact.follow.twitter': 'X',
    'contact.follow.instagram': 'Instagram',
    'footer.about.title': '会社概要',
    'footer.about.description': '私たちは、社会と地球にポジティブな影響を与える革新的なソリューションを作成することに取り組むテクノロジー企業です。',
    'footer.quicklinks': 'クイックリンク',
    'footer.services': 'サービス',
    'services.subtitle': '最先端のテクノロジーソリューションでビジネスを変革',
    'services.cta': '今すぐ始める',
    'footer.contact': 'お問い合わせ',
    'footer.follow': 'フォローする',
    'footer.copyright': '© {year} SafCom by Safar & Safarudin. All Rights Reserved.',
    'footer.services.web': 'ウェブ開発',
    'footer.services.mobile': 'モバイルアプリ',
    'footer.services.cloud': 'クラウドソリューション',
    'footer.services.ai': 'AI & 機械学習',
    'services.web.description': 'お客様のビジネスニーズに合わせたカスタムソフトウェアソリューションを、最新技術とベストプラクティスで構築します。',
    'services.mobile.description': 'iOSおよびAndroid向けのネイティブおよびクロスプラットフォームモバイルアプリケーションで、優れたユーザー体験を提供します。',
    'services.cloud.description': 'Azure、AWS、またはGCPでのスケーラブルなクラウドソリューションで、アプリケーションが効率的かつ安全に実行されることを保証します。',
    'services.ai.description': '機械学習モデル、データ分析、インテリジェントオートメーションを含む最先端のAIソリューション。',
    'team.title': 'チーム紹介',
    'team.subtitle': '情熱的なイノベーターが一緒にテクノロジーの未来を推進',
    'team.autoplay.pause': '自動再生を一時停止',
    'team.autoplay.resume': '自動再生を再開',
    'team.members.1.name': 'アレックス・ジョンソン',
    'team.members.1.role': '最高技術責任者',
    'team.members.1.bio': 'フルスタック開発の専門家で、10年以上の経験を持つ。スケーラブルなアーキテクチャとクラウドソリューションの設計を専門とする。',
    'team.members.2.name': 'サラ・チェン',
    'team.members.2.role': 'UX/UIデザイナー',
    'team.members.2.bio': 'ユーザビリティと美しさを融合させたデザインのスペシャリスト。ユーザーのニーズを理解し、革新的なソリューションを提供する。',
    'team.members.3.name': 'マイク・ロドリゲス',
    'team.members.3.role': 'バックエンド開発者',
    'team.members.3.bio': 'データベース設計とAPI開発のエキスパート。パフォーマンスとセキュリティを重視した堅牢なシステムを構築する。',
    'team.members.4.name': 'エマ・ウィリアムズ',
    'team.members.4.role': 'フロントエンド開発者',
    'team.members.4.bio': 'ReactとVue.jsのスペシャリスト。インタラクティブでレスポンシブなユーザーインターフェースを作成する。',
    'team.members.5.name': 'デイビッド・リー',
    'team.members.5.role': 'DevOpsエンジニア',
    'team.members.5.bio': 'CI/CDパイプラインとインフラ自動化の専門家。効率的で信頼性の高いデプロイメントプロセスを構築する。',
    'team.members.6.name': 'リサ・ガルシア',
    'team.members.6.role': 'プロジェクトマネージャー',
    'team.members.6.bio': 'アジャイル手法のエキスパート。チームをまとめ、プロジェクトを期限内に成功に導く。',
    'team.social.linkedin': 'LinkedIn',
    'team.social.github': 'GitHub',
    'team.social.twitter': 'Twitter',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['id', 'en', 'ja'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}